name: "Install Dependencies"
description: "Install the requirements"
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: |
          cd .github/scripts
          pip3 install --upgrade --no-cache-dir -r requirements.txt
          sudo apt install -y tree
        shell: bash
