name: "Set up Python"
description: "Shared action for ensuring consistent Python version across all CI jobs"
runs:
  using: "composite"
  steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
