name: update_community_plugin_issue_list
on:
  schedule:
    - cron: "59 23 * * 3"
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

jobs:
  update_issues:
    runs-on: ubuntu-latest

    # Prevent cron job from triggering on forks
    if: github.repository_owner == 'obsidian-community'

    steps:
      # ----------------------------------------------------------------------------------
      # Setup
      # ----------------------------------------------------------------------------------
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/install-dependencies
      - uses: ./.github/actions/setup-git-config

      # ----------------------------------------------------------------------------------
      # Run scripted update of community plugin issues with labels
      # ----------------------------------------------------------------------------------
      - name: Update list of community plugin issues with labels
        run: |
          cd .github/scripts
          python3 ./update_issues.py --apikey ${{ secrets.TOKEN }}
          git commit -m "Update 'Plugins seeking help'" -a  || echo "nothing to commit"
          
      # ----------------------------------------------------------------------------------
      # Finalisation
      # ----------------------------------------------------------------------------------
      # Reference: https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update 'Plugins seeking help'
          branch: create-pull-request/${{ github.workflow }}
          labels: |
            scripted update

      - name: Show Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
